### ISSUE TITLE
devkitppc-rules Makefile hardcodes `/opt/devkitpro`

### ISSUE THREAD

**Issue by Thesola10** [devkitPro/devkitppc-rules#3]
This causes build tools such as Nix to fail, as the files end up in another directory than was specified with `$BUILD_DKPRO_INSTALLDIR` for example.

**Comment by WinterMute** [comment]
directories other than /opt/devkitpro are not supported.

devkitPro provide tools and libraries in a standardised form as a means to facilitate and enable collaboration in the homebrew community supported by our work. Part of that is having a standard location due to the nature of the libraries we provide to facilitate porting work which expect to be installed in a fixed location & end up with that fixed location embedded in the libraries, scripts & ancillary tools they provide.

It is, of course, assumed that users of our tools have permission to install them on the machines they're using.
