### ISSUE TITLE
New Make setup

### ISSUE THREAD

**Issue by pyorot** [devkitPro/devkitppc-rules#9]
deleting links to projects we don't want others to see, are we?

**Comment by WinterMute** [comment]
Most users get along just fine with the Makefile system we have, don't be misled by a vocal minority who, for the most part, don't really understand what it was we set out to solve by building the system. There are some issues of course and, with the benefit of hindsight, I would perhaps have gone for a slightly different approach. We have looked at ways to try and improve things many times over the years but they all ultimately seem to add complexity for no particularly good reason, as yours does.

The salient paragraph of ["The confusion of cats"](https://davejmurphy.com/the-confusion-of-cats/) is this one. 

> We do need help with many things and it would be good if people approached us before embarking on huge projects that will impact on all the toolchain users. Ideally we’d like to see more collaboration towards making things better for everyone and we have very strong opinions on how that can work best but we need more people who understand the vision. We need more people who don’t buy into the diversity and competition myth, who understand the paradox of choice and who are willing to contribute for the greater good.

I hate rejecting efforts like this, you've obviously put in a lot of work but unfortunately it seems to me that the purpose of the build system in the first place has been misunderstood and, if I'm honest, the points you make seem kind of wrong headed in the first place. Used properly the Makefiles we provide recurse once so any performance enhancement from not recursing is really quite minimal. There are also aspects of the work you've done that really belong in libogc where they can be used by everyone and not just the homebrewers who copy what you've done into their own projects where will become fragmented and messed around with to the point that ultimately something we do in devkitPro tooling will break it and users are being advised to vandalise the infrastructure we created to support many projects for the sake of a single project for a single platform.

Currently we're looking at using cmake instead while preserving the Makefile based system we built over many years for the sake of older homebrew projects. Adding a third buildsystem makes no sense and simply adds to an already heavy maintenance burden. It would have been better to ask us about the problems you had with the existing system first rather than reinventing it then coming to ask.

**Comment by pyorot** [comment]
freeze peach

**Comment by WinterMute** [comment]
> an into irrecoverable dead ends twice trying to get the existing Makefile setup to work the way i wanted it to

This, most often, is simply trying to use the build system in a way it was never intended to be used and not understanding what it was designed for in the first place. I understand you're protective of all the time and effort you put into this but, from our perspective, you took several wrong turns which make it impossible for us to make use of or recommend the approach you've taken. C and C++ aren't Go and language paradigms often don't translate well. Libraries should, for the most part be provided externally, not just chucked in a source tree. We were also endlessly attempting to get people to use the build system provided by projects they were trying to port & not just slapping a Makefile in place of autotools, cmake or meson. Unfortunately many people refused to listen because it was "too hard" despite our best efforts to smooth the way.

The simple explanation is that it was intended to promote the use of Makefiles and dependency tracking in a world where people were trying to build whole projects by putting the whole command line in a batch file.

This is an issue tracker though, it isn't a discussion board.
